### ISSUE TITLE
Allow --config .myconfig.js

### ISSUE THREAD

**Issue by kaelig** [pa11y/pa11y-ci#39]
At the moment, passing a JS config fails. It'd be nice if you could pass something other than JSON!

---

Note: there's a known workaround.

This will load `.pa11yci.js` if it exists:

```
$ pa11y-ci
```

**Comment by rowanmanning** [comment]
That's odd, we explicitly support `.js` config files. Could you maybe share yours and the command that you're running? I'll try and work out what's going wrong

**Comment by kaelig** [comment]
I tried with `pa11y-ci --config .pa11yci.js`

When I traced it back, I think I ended up looking at this line

https://github.com/pa11y/pa11y-ci/blob/master/bin/pa11y-ci.js#L117

And I think it's trying to load the JS file (which fails).

**Comment by rowanmanning** [comment]
OK this seems to be working for me. Could you try the following config/command?

**`.pa11yci.js`:**
```js
module.exports = {
	defaults: {
		concurrency: 5
	},
	urls: [
		'https://www.ft.com/',
		'https://www.ft.com/world',
		'https://www.ft.com/life-arts'
	]
};
```

```sh
pa11y-ci
```

**Comment by kaelig** [comment]
This already works for us 🤗. What doesn’t seem to work is when passing a config option that points to a JS file.

**Comment by rowanmanning** [comment]
Ah, sorry I misunderstood. You're right, this is slightly broken – `.js` config files _are_ loaded but only if you leave out the `.js` extension in the flag.

I've fixed in #40, should merge and release soon! Thanks for reporting :)

**Comment by rowanmanning** [comment]
OK I've released version `1.3.1`, this should be fixed. Thanks again for bringing to my attention, @kaelig

**Comment by kaelig** [comment]
Brilliant, thank you Rowan!

**Comment by kaelig** [comment]
@rowanmanning seems like this bug is back - may have been back in there for a while… not sure!
